// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCwCYcR_jpx4z1Ck8ivnHc3NN98ntFC98',
    appId: '1:550994012595:web:7bde573ec256e8051543c6',
    messagingSenderId: '550994012595',
    projectId: 'gclassroommidyear',
    authDomain: 'gclassroommidyear.firebaseapp.com',
    storageBucket: 'gclassroommidyear.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_QZPQ9oOYr4hzG4QmMT_VHNKxnuhNfKc',
    appId: '1:550994012595:android:621753d7d023a6121543c6',
    messagingSenderId: '550994012595',
    projectId: 'gclassroommidyear',
    storageBucket: 'gclassroommidyear.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXhBo6jFgL2Zz3oLU6DMY7xpMV0FeCag4',
    appId: '1:550994012595:ios:b4a2e84a19e4cb8b1543c6',
    messagingSenderId: '550994012595',
    projectId: 'gclassroommidyear',
    storageBucket: 'gclassroommidyear.appspot.com',
    androidClientId: '550994012595-3eoa3vv5v9car4qsnm9kli5843kmvkt5.apps.googleusercontent.com',
    iosBundleId: 'com.example.todolist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXhBo6jFgL2Zz3oLU6DMY7xpMV0FeCag4',
    appId: '1:550994012595:ios:2cb367845f34c8241543c6',
    messagingSenderId: '550994012595',
    projectId: 'gclassroommidyear',
    storageBucket: 'gclassroommidyear.appspot.com',
    androidClientId: '550994012595-3eoa3vv5v9car4qsnm9kli5843kmvkt5.apps.googleusercontent.com',
    iosBundleId: 'com.example.todolist.RunnerTests',
  );
}
